#!/bin/bash

# Set working directory to the location of this script
cd "$(dirname "$0")";

LOGINSERVER=$(ps ax | grep ./login-server | grep -v grep | wc -l)
CHARSERVER=$(ps ax | grep ./char-server | grep -v grep | wc -l)
MAPSERVER=$(ps ax | grep ./map-server | grep -v grep | wc -l)

if [ $LOGINSERVER -eq 0 ]
then
	nohup ./login-server &> logs/nohup.out &
fi

if [ $CHARSERVER -eq 0 ]
then
	nohup ./char-server &> logs/nohup.out &
fi

if [ $MAPSERVER -eq 0 ]
then
	nohup ./map-server &> logs/nohup.out &
fi
